# Generated by Django 5.0.7 on 2024-07-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fule_name', models.CharField(max_length=50)),
                ('car', models.ManyToManyField(to='app.car')),
            ],
        ),
    ]
